// flow-typed signature: aa4f166b7b830ed3ca4f305af008f12f
// flow-typed version: <<STUB>>/browser-env_v^3.1.2/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'browser-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'browser-env' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'browser-env/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'browser-env/src/index.js' {
  declare module.exports: $Exports<'browser-env/src/index'>;
}
