// flow-typed signature: 9f3b6de91551cb0a9e3a4ce85dfc0f1f
// flow-typed version: <<STUB>>/vue-hoc_vfile:../vue-hoc/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-hoc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-hoc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-hoc/dist/annotations' {
  declare module.exports: any;
}

declare module 'vue-hoc/dist/courier' {
  declare module.exports: any;
}

declare module 'vue-hoc/dist/createHOC' {
  declare module.exports: any;
}

declare module 'vue-hoc/dist/createRenderFn' {
  declare module.exports: any;
}

declare module 'vue-hoc/dist/index' {
  declare module.exports: any;
}

declare module 'vue-hoc/dist/normalizeSlots' {
  declare module.exports: any;
}

declare module 'vue-hoc/flow-typed/npm/babel-cli_vx.x.x' {
  declare module.exports: any;
}

declare module 'vue-hoc/flow-typed/npm/babel-core_vx.x.x' {
  declare module.exports: any;
}

declare module 'vue-hoc/flow-typed/npm/babel-preset-env_vx.x.x' {
  declare module.exports: any;
}

declare module 'vue-hoc/flow-typed/npm/babel-preset-flow_vx.x.x' {
  declare module.exports: any;
}

declare module 'vue-hoc/flow-typed/npm/browser-env_vx.x.x' {
  declare module.exports: any;
}

declare module 'vue-hoc/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'vue-hoc/flow-typed/npm/inspect-process_vx.x.x' {
  declare module.exports: any;
}

declare module 'vue-hoc/flow-typed/npm/require-extension-hooks_vx.x.x' {
  declare module.exports: any;
}

declare module 'vue-hoc/flow-typed/npm/require-extension-hooks-babel_vx.x.x' {
  declare module.exports: any;
}

declare module 'vue-hoc/flow-typed/npm/sinon_vx.x.x' {
  declare module.exports: any;
}

declare module 'vue-hoc/flow-typed/npm/vue_vx.x.x' {
  declare module.exports: any;
}

declare module 'vue-hoc/flow-typed/npm/vuenit_vx.x.x' {
  declare module.exports: any;
}

declare module 'vue-hoc/spec/createHOC.spec' {
  declare module.exports: any;
}

declare module 'vue-hoc/spec/events.spec' {
  declare module.exports: any;
}

declare module 'vue-hoc/spec/functional.spec' {
  declare module.exports: any;
}

declare module 'vue-hoc/spec/hooks' {
  declare module.exports: any;
}

declare module 'vue-hoc/spec/hooks.spec' {
  declare module.exports: any;
}

declare module 'vue-hoc/spec/props.spec' {
  declare module.exports: any;
}

declare module 'vue-hoc/spec/slots.spec' {
  declare module.exports: any;
}

declare module 'vue-hoc/src/annotations' {
  declare module.exports: any;
}

declare module 'vue-hoc/src/courier' {
  declare module.exports: any;
}

declare module 'vue-hoc/src/createHOC' {
  declare module.exports: any;
}

declare module 'vue-hoc/src/createRenderFn' {
  declare module.exports: any;
}

declare module 'vue-hoc/src/index' {
  declare module.exports: any;
}

declare module 'vue-hoc/src/normalizeSlots' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-hoc/dist/annotations.js' {
  declare module.exports: $Exports<'vue-hoc/dist/annotations'>;
}
declare module 'vue-hoc/dist/courier.js' {
  declare module.exports: $Exports<'vue-hoc/dist/courier'>;
}
declare module 'vue-hoc/dist/createHOC.js' {
  declare module.exports: $Exports<'vue-hoc/dist/createHOC'>;
}
declare module 'vue-hoc/dist/createRenderFn.js' {
  declare module.exports: $Exports<'vue-hoc/dist/createRenderFn'>;
}
declare module 'vue-hoc/dist/index.js' {
  declare module.exports: $Exports<'vue-hoc/dist/index'>;
}
declare module 'vue-hoc/dist/normalizeSlots.js' {
  declare module.exports: $Exports<'vue-hoc/dist/normalizeSlots'>;
}
declare module 'vue-hoc/flow-typed/npm/babel-cli_vx.x.x.js' {
  declare module.exports: $Exports<'vue-hoc/flow-typed/npm/babel-cli_vx.x.x'>;
}
declare module 'vue-hoc/flow-typed/npm/babel-core_vx.x.x.js' {
  declare module.exports: $Exports<'vue-hoc/flow-typed/npm/babel-core_vx.x.x'>;
}
declare module 'vue-hoc/flow-typed/npm/babel-preset-env_vx.x.x.js' {
  declare module.exports: $Exports<'vue-hoc/flow-typed/npm/babel-preset-env_vx.x.x'>;
}
declare module 'vue-hoc/flow-typed/npm/babel-preset-flow_vx.x.x.js' {
  declare module.exports: $Exports<'vue-hoc/flow-typed/npm/babel-preset-flow_vx.x.x'>;
}
declare module 'vue-hoc/flow-typed/npm/browser-env_vx.x.x.js' {
  declare module.exports: $Exports<'vue-hoc/flow-typed/npm/browser-env_vx.x.x'>;
}
declare module 'vue-hoc/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'vue-hoc/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'vue-hoc/flow-typed/npm/inspect-process_vx.x.x.js' {
  declare module.exports: $Exports<'vue-hoc/flow-typed/npm/inspect-process_vx.x.x'>;
}
declare module 'vue-hoc/flow-typed/npm/require-extension-hooks_vx.x.x.js' {
  declare module.exports: $Exports<'vue-hoc/flow-typed/npm/require-extension-hooks_vx.x.x'>;
}
declare module 'vue-hoc/flow-typed/npm/require-extension-hooks-babel_vx.x.x.js' {
  declare module.exports: $Exports<'vue-hoc/flow-typed/npm/require-extension-hooks-babel_vx.x.x'>;
}
declare module 'vue-hoc/flow-typed/npm/sinon_vx.x.x.js' {
  declare module.exports: $Exports<'vue-hoc/flow-typed/npm/sinon_vx.x.x'>;
}
declare module 'vue-hoc/flow-typed/npm/vue_vx.x.x.js' {
  declare module.exports: $Exports<'vue-hoc/flow-typed/npm/vue_vx.x.x'>;
}
declare module 'vue-hoc/flow-typed/npm/vuenit_vx.x.x.js' {
  declare module.exports: $Exports<'vue-hoc/flow-typed/npm/vuenit_vx.x.x'>;
}
declare module 'vue-hoc/spec/createHOC.spec.js' {
  declare module.exports: $Exports<'vue-hoc/spec/createHOC.spec'>;
}
declare module 'vue-hoc/spec/events.spec.js' {
  declare module.exports: $Exports<'vue-hoc/spec/events.spec'>;
}
declare module 'vue-hoc/spec/functional.spec.js' {
  declare module.exports: $Exports<'vue-hoc/spec/functional.spec'>;
}
declare module 'vue-hoc/spec/hooks.js' {
  declare module.exports: $Exports<'vue-hoc/spec/hooks'>;
}
declare module 'vue-hoc/spec/hooks.spec.js' {
  declare module.exports: $Exports<'vue-hoc/spec/hooks.spec'>;
}
declare module 'vue-hoc/spec/props.spec.js' {
  declare module.exports: $Exports<'vue-hoc/spec/props.spec'>;
}
declare module 'vue-hoc/spec/slots.spec.js' {
  declare module.exports: $Exports<'vue-hoc/spec/slots.spec'>;
}
declare module 'vue-hoc/src/annotations.js' {
  declare module.exports: $Exports<'vue-hoc/src/annotations'>;
}
declare module 'vue-hoc/src/courier.js' {
  declare module.exports: $Exports<'vue-hoc/src/courier'>;
}
declare module 'vue-hoc/src/createHOC.js' {
  declare module.exports: $Exports<'vue-hoc/src/createHOC'>;
}
declare module 'vue-hoc/src/createRenderFn.js' {
  declare module.exports: $Exports<'vue-hoc/src/createRenderFn'>;
}
declare module 'vue-hoc/src/index.js' {
  declare module.exports: $Exports<'vue-hoc/src/index'>;
}
declare module 'vue-hoc/src/normalizeSlots.js' {
  declare module.exports: $Exports<'vue-hoc/src/normalizeSlots'>;
}
